f = open(r'C:\Users\Admin\perm-crm\web\app\login\page.tsx', 'w')
lines = [
'"use client";\n',
'import { useState } from "react";\n',
'import { useRouter } from "next/navigation";\n',
'\n',
'const API = process.env.NEXT_PUBLIC_API_BASE_URL || "http://localhost:8000";\n',
'\n',
'export default function LoginPage() {\n',
'  const [email, setEmail] = useState("planning@permitas.co.uk");\n',
'  const [password, setPassword] = useState("");\n',
'  const [error, setError] = useState("");\n',
'  const [loading, setLoading] = useState(false);\n',
'  const router = useRouter();\n',
'\n',
'  const login = async (e: React.FormEvent) => {\n',
'    e.preventDefault();\n',
'    setLoading(true);\n',
'    setError("");\n',
'    try {\n',
'      const res = await fetch(API+"/login", {\n',
'        method: "POST",\n',
'        headers: { "Content-Type": "application/json" },\n',
'        body: JSON.stringify({ email, password }),\n',
'      });\n',
'      if (!res.ok) { setError("Invalid email or password"); setLoading(false); return; }\n',
'      const data = await res.json();\n',
'      localStorage.setItem("token", data.access_token);\n',
'      localStorage.setItem("user_name", data.name);\n',
'      localStorage.setItem("user_email", data.email);\n',
'      router.push("/");\n',
'    } catch(e) {\n',
'      setError("Cannot connect to server");\n',
'    } finally {\n',
'      setLoading(false);\n',
'    }\n',
'  };\n',
'\n',
'  return (\n',
'    <main className="min-h-screen flex items-center justify-center bg-slate-900">\n',
'      <div className="w-full max-w-md">\n',
'        <div className="text-center mb-8">\n',
'          <h1 className="text-3xl font-bold text-white mb-2">Perm CRM</h1>\n',
'          <p className="text-slate-400">Permitas Planning Consultants</p>\n',
'        </div>\n',
'        <div className="bg-white rounded-2xl shadow-xl p-8">\n',
'          <h2 className="text-xl font-bold text-slate-800 mb-6">Sign in</h2>\n',
'          {error && (\n',
'            <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg mb-4 text-sm">{error}</div>\n',
'          )}\n',
'          <form onSubmit={login} className="space-y-4">\n',
'            <div>\n',
'              <p className="text-xs font-semibold text-slate-500 uppercase mb-1">Email</p>\n',
'              <input type="email" className="w-full border border-slate-200 rounded-lg px-4 py-3 text-sm" value={email} onChange={e=>setEmail(e.target.value)} required />\n',
'            </div>\n',
'            <div>\n',
'              <p className="text-xs font-semibold text-slate-500 uppercase mb-1">Password</p>\n',
'              <input type="password" className="w-full border border-slate-200 rounded-lg px-4 py-3 text-sm" value={password} onChange={e=>setPassword(e.target.value)} placeholder="permitas2026" required />\n',
'            </div>\n',
'            <button type="submit" disabled={loading} className="w-full bg-emerald-700 text-white py-3 rounded-lg font-semibold text-sm hover:bg-emerald-800">\n',
'              {loading ? "Signing in..." : "Sign In"}\n',
'            </button>\n',
'          </form>\n',
'          <div className="mt-4 p-3 bg-slate-50 rounded-lg">\n',
'            <p className="text-xs text-slate-500">Email: planning@permitas.co.uk</p>\n',
'            <p className="text-xs text-slate-500">Password: permitas2026</p>\n',
'          </div>\n',
'        </div>\n',
'      </div>\n',
'    </main>\n',
'  );\n',
'}\n',
]
f.writelines(lines)
f.close()
print("Login page created!")